familybudgetapp/familybudget/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import index, add, delete, add_to_budget, take_from_budget, add_element_to_budget, \
    delete_element_from_budget, CustomLoginView, CustomRegisterView, BudgetViewSet, BudgetElementViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'budgets', BudgetViewSet)
router.register(r'elements', BudgetElementViewSet)

urlpatterns = [
    path('', index, name='index'),
    path('add', add, name='add'),
    path('delete/<int:budget_id>/', delete, name='delete'),
    path('add_to_budget/<int:budget_id>/', add_to_budget, name='add_to_budget'),
    path('take_from_budget/<int:budget_id>/', take_from_budget, name='take_from_budget'),
    path('add_element_to_budget/<int:budget_id>/', add_element_to_budget, name='add_element_to_budget'),
    path('delete_element_from_budget/<int:element_id>/', delete_element_from_budget, name='delete_element_from_budget'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', CustomRegisterView.as_view(), name='register',),
    # path('api/', index(router.urls))
]

familybudgetapp/familybudgetapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('familybudget.urls'))
]

familybudgetapp/familybudget/models.py
from django.db import models
from django.contrib.auth.models import User


CATEGORIES = (
    ('food', 'Food'),
    ('utilities', 'Utilities'),
    ('clothing', 'Clothing'),
    ('transport', 'Transport'),
    ('payments', 'Payments'),
    ('uncategorized', 'Uncategorized')
)

GROUPS = (
    ('private', 'Private'),
    ('family', 'Family')
)


class Budget(models.Model):
    user = models.ForeignKey(User, models.CASCADE, null=False, blank=False)
    title = models.CharField(max_length=100, null=False, blank=False)
    amount_of_budget = models.IntegerField(null=False, blank=False)
    complete = models.BooleanField(default=False)
    category = models.CharField(max_length=20, choices=CATEGORIES, default='uncategorized')
    group = models.CharField(max_length=20, choices=GROUPS, default='private')

    def __str__(self):
        return self.title


class BudgetElement(models.Model):
    user = models.ForeignKey(User, models.CASCADE, null=False, blank=False)
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE, null=False, blank=False)
    description_of_element = models.CharField(max_length=250, null=False, blank=False)
    value_of_element = models.IntegerField(null=False, blank=False)

    def __str__(self):
        return self.description_of_element

familybudgetapp/familybudget/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView
from rest_framework import viewsets

from .models import Budget, BudgetElement
from .filter import BudgetFilter
from .serializers import BudgetSerializer, BudgetElementSerializer


class BudgetViewSet(viewsets.ModelViewSet):
    queryset = Budget.objects.all()
    serializer_class = BudgetSerializer


class BudgetElementViewSet(viewsets.ModelViewSet):
    queryset = BudgetElement.objects.all()
    serializer_class = BudgetElementSerializer


class CustomLoginView(LoginView):
    template_name = 'login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('index')


class CustomRegisterView(FormView):
    template_name = 'register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(CustomRegisterView, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('index')
        return super(CustomRegisterView, self).get(*args, **kwargs)


@login_required(login_url='login')
def index(request):
    queryset = Budget.objects.all()
    filterset = BudgetFilter(data=request.GET, queryset=queryset)
    budgets = filterset.qs
    budget_elems = BudgetElement.objects.all()
    return render(request, 'family_budget_base.html', {
        'filter': filterset,
        'budget_list': budgets,
        'budget_element_list': budget_elems})


@require_http_methods(['POST'])
def add(request):
    user = request.user
    title = request.POST['title']
    amount_of_budget = request.POST['amount_of_budget']
    category = request.POST['category']
    group = request.POST['group']
    budget = Budget(user=user, title=title, amount_of_budget=amount_of_budget, category=category, group=group)
    budget.save()
    return redirect('index')


def add_to_budget(request, budget_id):
    budget = Budget.objects.get(id=budget_id)
    budget.amount_of_budget += int(request.POST['add_to_budget'])
    budget.save()
    return redirect('index')


def add_element_to_budget(request, budget_id):
    user = request.user
    budget = Budget.objects.get(id=budget_id)
    description_of_element = request.POST['description_of_element']
    value_of_element = request.POST['value_of_element']
    budget_element = BudgetElement(user=user, budget=budget, description_of_element=description_of_element,
                                   value_of_element=value_of_element)
    budget.amount_of_budget -= int(value_of_element)
    budget_element.save()
    budget.save()
    return redirect('index')


def delete_element_from_budget(request, element_id):
    budget_element = BudgetElement.objects.get(id=element_id)
    budget = budget_element.budget
    budget.amount_of_budget += budget_element.value_of_element
    budget.save()
    budget_element.delete()
    return redirect('index')


def take_from_budget(request, budget_id):
    budget = Budget.objects.get(id=budget_id)
    budget.amount_of_budget -= int(request.POST['take_from_budget'])
    budget.save()
    return redirect('index')


def delete(request, budget_id):
    budget = Budget.objects.get(id=budget_id)
    budget.delete()
    return redirect('index')

familybudgetapp/templates/family_budget_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Family Budget</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body class="p-3 m-0 border-0 bd-example">
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Family Budget by Patryk Janas</a>
        <div class="nav navbar-nav navbar-right" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <p class="nav-link active" aria-current="page"
                       style="text-transform: capitalize">{{ request.user }}</p>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div style="margin-top: 50px;" class="ui container">
    <form method="GET">
        {{ filter.form }}
        <button type="submit">Filter</button>
    </form>
    <br>

    {% for budget in filter.qs %}
        <div>
            <table class="table mb-4">
                <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Title</th>
                    <th scope="col">Budget left</th>
                    <th scope="col">Category</th>
                    <th scope="col">Group</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <tr class="accordion-toggle collapsed" id="accordion1" data-toggle="collapse" data-parent="#accordion1"
                    href="#collapseOne">
                    <th scope="row">{{ budget.id }}</th>
                    <td>{{ budget.title }}</td>
                    <td>{{ budget.amount_of_budget }} zł</td>
                    <td>{{ budget.get_category_display }}</td>
                    <td>{{ budget.get_group_display }}</td>
                    <td>
                        <a class="btn btn-danger" href="/delete/{{ budget.id }}/">Delete</a>
                        <a class="btn btn-primary" data-bs-toggle="collapse" href="#elementsCollapse{{ budget.id }}" role="button"
                           aria-expanded="false" aria-controls="elementsCollapse">Show elements</a>
                        <a class="btn btn-warning" data-bs-toggle="collapse" href="#elementAddCollapse{{ budget.id }}" role="button"
                           aria-expanded="false" aria-controls="elementAddCollapse{{ budget.id }}">Add element</a>

                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="row">
        <div class="col">
        <div class="collapse multi-collapse" id="elementsCollapse{{ budget.id }}">
            <div class="card card-body">
                {% for element in budget_element_list %}
                    {% if element.budget.id == budget.id %}
                        <table class="table mb-4">
                            <thead>
                            <tr>
                                <th scope="col">No.</th>
                                <th scope="col">Element name</th>
                                <th scope="col">Cost of element</th>
                                <th scope="col">Actions on element</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="accordion-toggle collapsed" id="accordion1" data-toggle="collapse"
                                data-parent="#accordion1"
                                href="#collapseOne">
                                <th scope="row">{{ element.id }}</th>
                                <td>{{ element.description_of_element }}</td>
                                <td>{{ element.value_of_element }} zł</td>
                                <td>
                                    <a class="btn btn-secondary" href="/delete_element_from_budget/{{ element.id }}/">
                                        Remove element</a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        </div>
        </div>
        <div class="collapse multi-collapse" id="elementAddCollapse{{ budget.id }}">
            <form class="row gy-2 gx-3 align-items-center" action="/add_element_to_budget/{{ budget.id }}/"
                  method="post">
                {% csrf_token %}
                <div class="col-auto">
                    <div class="form-outline">
                        <input type="text" id="form11Example1" class="form-control" name="description_of_element"
                               placeholder="Description of element"/>
                    </div>
                </div>
                <div class="col-auto">
                    <div class="form-outline">
                        <input type="text" id="form11Example3" class="form-control" name="value_of_element"
                               placeholder="Value of element"/>
                    </div>
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-warning">Add element</button>
                </div>
            </form>
        </div>
    {% endfor %}
    <hr>
    <h3 class="ui center aligned header">Add Budget</h3>
    <hr>
    <form class="row gy-2 gx-3 align-items-center" action="/add" method="post">
        {% csrf_token %}
        <div class="col-auto">
            <div class="form-outline">
                <input type="text" id="form11Example1" class="form-control" name="title" placeholder="Budget Title"/>
            </div>
        </div>
        <div class="col-auto">
            <div class="form-outline">
                <input type="text" id="form11Example3" class="form-control" name="amount_of_budget"
                       placeholder="Budget Amount"/>
            </div>
        </div>
        <div class="col-auto">
            <select class="form-select" name="category" id="category" aria-label="Floating label select example">
                <option selected>Select category</option>
                <option value="food">Food</option>
                <option value="transport">Transport</option>
                <option value="payments">Payments</option>
                <option value="uncategorized">Uncategorized</option>
            </select>
        </div>
        <div class="col-auto">
            <select class="form-select" name="group" id="group" aria-label="Floating label select example">
                <option selected>Select group</option>
                <option value="private">Private</option>
                <option value="family">Family</option>
            </select>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
            integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
            crossorigin="anonymous"></script>

</body>
</html>

familybudgetapp/templates/login.html
<h1>LOGIN</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>

<p>If U don't have an account - <a href='{% url "register" %}'>Create one!</a></p>

familybudgetapp/templates/register.html
<h1>REGISTER</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>

<p>Already have an account - <a href='{% url "login" %}'>Login</a></p>